title: Canon com ijsetup | ij.start.canon
description: Setup wireless canon printer with your preferred device using the steps given at ij.start.canon setup. Enter canon printer model number and download the software.
